services:
  - type: web
    name: ai-booking-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_FILE
        value: ./service-account-key.json
      - key: GOOGLE_CALENDAR_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    
  - type: web
    name: ai-booking-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://ai-booking-backend.onrender.com